#! /bin/sh

FILE="$1"
MIME="$(file --mime-type -bL "$FILE")"
EXT="${FILE##*.}"
[ -t 1 ] && TTY='yes' || TTY='no'

orphan() {
	{ nohup "$@" & } &>/dev/null </dev/null  &
}

# Handle links
case "$(echo "$FILE" | cut -d: -f1)" in
	magnet) orphan tremc-notify "$FILE"; exit ;;
esac

# Handle mimetype
case "$MIME" in
	image/*) orphan sxiv "$FILE" *; exit ;;
esac

# Handle extension
case "$EXT" in
esac

# Open every txt file in EDITOR
# I might need to open a txt file in another app, but I don't right now
if [ "$(file -bL --mime-encoding "$FILE")" != 'binary' ] && [ "$TTY" = yes ]; then
	$EDITOR "$FILE"
	exit
fi

/usr/bin/xdg-open "${FILE}"
