#!/bin/sh
# adds files using glob patterns to yadm repo

# export package list
pacman -Qqen > ~/.config/yadm/arch
pacman -Qqem > ~/.config/yadm/aur

sudo apack ~/conns.zip /etc/NetworkManager/system-connections

yadm encrypt
yadm add -f .librewolf/librewolf.overrides.cfg
yadm add -f .local/share/yadm/archive
yadm add -f .bin
yadm add -f .Xresources
yadm add -f .cargo/.crates.toml
yadm add -f .gitconfig
yadm add -f .irssi/config
yadm add -f .newsboat/urls
yadm add -f .paclist
yadm add -f .rustup/settings.toml
yadm add -f .terminfo
yadm add -f .theme
yadm add -f .tmux.conf
yadm add -f .todo.md
yadm add -f .readme.md
yadm add -f .walls
yadm add -f .xinitrc
yadm add -f .config/{DIR_COLORS,alacritty,dunst,fish,fontconfig,gitui,gtk*,helix,htop,hypr,kak{,-lsp},kickoff,lapce*.toml,lf,libresprite/palettes,lite-xl,nwg*,mimeapps.list,mpd,ncmpcpp,picom.conf,polybar,rustfmt,river,swappy,sxhkd,systemd,tremc,yadm,yay,tofi,waybar,zathura,bspwm,calibre,compton}
yadm commit -m "$(date)"
